// Auto-generated by OpenLane
module mbist_ctrl(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst,
  input start,
  input[7:0] mem_dout,
  output[7:0] mem_addr,
  output[7:0] mem_din,
  output mem_we,
  output mem_ce,
  output done,
  output pass_fail,
  output[7:0] diag_addr
);
endmodule
